version: '3'

services:
  aviasales_back:
    image: aviasales-back
    build:
      context: ./backend
    restart: always
    ports:
      - "5000:80"
  aviasales_front:
    image: aviasales-front
    build:
      context: ./frontend
    restart: always
    ports:
      - "8888:80"
    environment:
      - API=http://localhost:5000
